apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-webhook-configmap
  namespace: {{ .Values.namespace }}
data:
  sidecarconfig.yaml: |
    volumes:
      - emptyDir:
          medium: Memory
        name: tokens
    volumeMounts:
      - mountPath: /etc/tokens
        name: tokens
    containers:
      - name: simple-sidecar
        image: registry.hub.docker.com/library/busybox
  mutationconfig.yaml: |
    mutationConfigs:
      - name: "simple-mutation-config"
        annotationNamespace: "simple-sidecar.k8s-integration.sfdc.com"
        annotationTrigger: "inject"
        containers: ["simple-sidecar"]
        volumes: ["tokens"]
        volumeMounts: ["tokens"]
        ignoreNamespaces: []