apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appname }}
      app.kubernetes.io/instance: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appname }}
        app.kubernetes.io/instance: {{ .Values.appname }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/webhook/config
              name: webhook-config
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          args:
            - /sidecarinjector
            - --port={{ .Values.service.targetPort }}
            - --sidecar-config-file=/etc/webhook/config/sidecarconfig.yaml
            - --mutation-config-file=/etc/webhook/config/mutationconfig.yaml
            - --cert-file-path=/etc/webhook/certs/tls.crt
            - --key-file-path=/etc/webhook/certs/tls.key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - configMap:
            name: {{ .Values.appname }}-webhook-configmap
          name: webhook-config
        - name: webhook-certs
          secret:
            secretName: {{ .Values.appname }}-certificate
